### ISSUE TITLE
NotFound errors on Deno Deploy

### ISSUE THREAD

**Issue by cdoremus** [cdoremus/deno-blog#6]
Occasionally, I see `NotFound` errors in the Deno Deploy logs like this
```
An error occurred during route handling or page rendering. NotFound: No such file or directory
    at async readFile (deno:deploy/js/02_fs.js:56:12)
    at async Object.readTextFile (deno:deploy/js/02_fs.js:64:17)
    at async GET (file:///src/routes/[name].tsx:10:26)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:107:36
    at async handler (file:///src/routes/_middleware.ts:2:18)
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:219:24)
2022-10-01 13:46:32
An error occurred during route handling or page rendering. NotFound: No such file or directory
    at async readFile (deno:deploy/js/02_fs.js:56:12)
    at async Object.readTextFile (deno:deploy/js/02_fs.js:64:17)
    at async GET (file:///src/routes/[name].tsx:10:26)
    at async https://deno.land/x/rutt@0.0.13/mod.ts:107:36
    at async handler (file:///src/routes/_middleware.ts:2:18)
    at async Server.#respond (https://deno.land/std@0.150.0/http/server.ts:219:24)

Listening on [http://localhost:80/](http://localhost/)
2022-10-01 13:46:25
northamerica-northeast1isolate start time: 2.16 ms
2022-10-01 13:46:25
```

**Comment by cdoremus** [comment]
Fixed a while ago
